api_key/urls.py
from django.urls import path, reverse_lazy
from api_key.views import ApiKeyUpdate

urlpatterns = [
    path('update', ApiKeyUpdate.as_view(success_url=reverse_lazy('api_user-profile')),
         name='api_key_update'),
]

api_user/urls.py
# from django.contrib import admin
from django.urls import path, reverse_lazy

from django.contrib.auth import views as auth_views
import api_user.views as api_user_views

# Registration & Login
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name="api_user-login"),
    path('logout/', auth_views.LogoutView.as_view(), name="api_user-logout"),
    # password reset
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        html_email_template_name='registration/password_reset_email.html'
    ), name="password_reset"),
    path('accounts/password_reset/confirm/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_email_sent.html'
    ), name="password_reset_done"),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html'
    ), name="password_reset_link"),
    path('accounts/password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'
    ), name="password_reset_complete"),
    # registration
    path('register/', api_user_views.RegisterView.as_view(), name="register"),
    # social auth
    # path('auth/', include('social_django.urls', namespace='social')),
]

# API User Dashboard
urlpatterns += [
    path('profile', api_user_views.ProfileUpdate.as_view(success_url=reverse_lazy('api_user-profile')),
         name='api_user-profile'),
    path('settings/api_user/password', api_user_views.UpdatePassword.as_view(success_url=reverse_lazy('api_user-profile')),
         name='api_user-password')
]

jobhound/urls.py
# from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from jobhound.views import JobViewSet

router = routers.DefaultRouter()
router.register('jobs', JobViewSet, basename='jobs')

# Registration & Login
urlpatterns = [
    path('', include('frontend.urls')),
    path('api_user/', include('api_user.urls')),
    path('api_key/', include('api_key.urls')),
]

urlpatterns += router.urls

api_key/models.py
from django.db import models
from api_user.models import ApiUser
import secrets


# Create your models here.

class APIKey(models.Model):
    user = models.ForeignKey(ApiUser, on_delete=models.CASCADE)
    api_key = models.CharField(max_length=128)
    is_active = models.BooleanField(default=True)

    @staticmethod
    def generate_key():
        key = secrets.token_urlsafe(16)
        return key
    
    def __unicode__(self):
        return self.api_key

api_user/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class ApiUser(User):
    def __str__(self):
        return self.email

api_user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Field
from api_user.models import ApiUser


class ApiUserSignupForm(UserCreationForm):
    class Meta:
        model = ApiUser
        fields = ('username', 'email')


class ApiUserUpdateForm(UserChangeForm):
    class Meta:
        model = ApiUser
        fields = ('username', 'email')

        def __init__(self):
            self.helper = FormHelper()
            self.helper.layout = Layout(
                'username',
                'email',
            )

api_user/views.py
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import render

# Create your views here.
from django.views.generic import CreateView, UpdateView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.views import PasswordChangeView
from api_user.mixins import LoginRequiredMixin

import logging

from api_user.models import ApiUser
from api_user.forms import ApiUserSignupForm, ApiUserUpdateForm
from api_user.decorators import check_recaptcha

from api_key.models import APIKey

main_logger = logging.getLogger('main')


class RegisterView(CreateView):
    model = ApiUser
    form_class = ApiUserSignupForm
    success_url = reverse_lazy('api_user-login')
    template_name = 'registration/signup.html'

    # @method_decorator(check_recaptcha)
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        # if form.is_valid() and request.recaptcha_valid:
        if form.is_valid(): #for debugging
            main_logger.info('api user registered account..')
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


def api_user_dashboard(request):
    return render(request, 'dashboard/main.html')


class ProfileUpdate(LoginRequiredMixin, UpdateView):
    model = ApiUser
    template_name = 'dashboard/account.html'
    form_class = ApiUserUpdateForm
    login_url = 'api_user-login'

    def get_object(self, queryset=None):
        return self.model.objects.get(user_ptr_id=self.request.user.id)

    # def get(self, request, *args, **kwargs):
    #     self.object = request.user
    #     return self.render_to_response(self.get_context_data())
    # 
    # def post(self, request, *args, **kwargs):
    #     self.object = self.model.objects.get(user_ptr_id=request.user.id)
    #     form = self.get_form()
    #     if form.is_valid():
    #         return self.form_valid(form)
    #     else:
    #         return self.form_invalid(form)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProfileUpdate, self).get_context_data(object_list=None, **kwargs)
        context['page'] = {
            'title': 'Update Profile',
            'bc1': 'Profile',
            'bc2': 'Update',
        }
        return context


class UpdatePassword(LoginRequiredMixin, PasswordChangeView):
    model = ApiUser
    template_name = 'dashboard/form.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UpdatePassword, self).get_context_data(object_list=None, **kwargs)
        context['page'] = {
            'title': 'Change Password',
            'bc1': 'Account',
            'bc2': 'Password',
        }
        return context


@receiver(post_save, sender=ApiUser)
def new_api_user(sender, **kwargs):
    api_user = kwargs['instance']
    if kwargs['created']:
        new_api_key = APIKey(
            user=api_user,
            api_key=APIKey.generate_key()
        )
        new_api_key.save()

api_user/templates/dashboard/account.html
{% extends 'skeleton/main.html' %}
{% load crispy_forms_tags %}

{% block title_header %}
    <div class="page-title-box">
        <h4 class="page-title">{{ page.title }}</h4>
        <ol class="breadcrumb float-right">
            <li class="breadcrumb-item"><a href="#">{{ page.bc1 }}</a></li>
            <li class="breadcrumb-item active">{{ page.bc2 }}</li>
        </ol>
        <div class="clearfix"></div>
    </div>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="card-box">
            {% for form_field in form %}
                {% if form_field.name != 'password' %}
                {{ form_field|as_crispy_field }}
                {% endif %}
            {% endfor %}
            <div class="control-group">
            <label for="">Key</label>
            <div class="alert alert-info">{{ object.apikey_set.first.api_key }}
            </div>
            </div>
            <p><a href="{% url 'api_user-password' %}">Change password</a></p>
            <p><a href="{% url 'api_key_update' %}">New API Key</a></p>
            <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </form>
{% endblock %}

api_user/templates/dashboard/form.html
{% extends 'skeleton/main.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title_header %}
    <div class="page-title-box">
        <h4 class="page-title">{{ page.title }}</h4>
        <ol class="breadcrumb float-right">
            <li class="breadcrumb-item"><a href="#">{{ page.bc1 }}</a></li>
            <li class="breadcrumb-item active">{{ page.bc2 }}</li>
        </ol>
        <div class="clearfix"></div>
    </div>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="card-box">
            
            {% crispy form %}
            
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
        </div>
    </form>
{% endblock %}

api_user/templates/dashboard/key.html
{% extends 'skeleton/main.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title_header %}
    <div class="page-title-box">
        <h4 class="page-title">{{ page.title }}</h4>
        <ol class="breadcrumb float-right">
            <li class="breadcrumb-item"><a href="#">{{ page.bc1 }}</a></li>
            <li class="breadcrumb-item active">{{ page.bc2 }}</li>
        </ol>
        <div class="clearfix"></div>
    </div>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="card-box">
            
            <p>{{ apikey.api_key }}</p>
            
            <button type="submit" class="btn btn-primary">New Key</button>
        </div>
        </div>
    </form>
{% endblock %}

api_user/templates/dashboard/main.html
<h1>DASHBOARD!!!</h1>